#! /bin/sh

# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>

#remote="$1"
#url="$2"

exec git submodule --quiet foreach --recursive "$(realpath cwm4/scripts/submodule_pre-push.sh)"' "$sm_path" $sha1 "$toplevel"'
