#! /bin/bash
# Written by Carlo Wood 2017

# Parse command line parameters.
opt_foreach=0
while [[ $# -gt 0 ]]
do
  case $1 in
    --foreach)
      opt_foreach=1
      ;;
    --)
      break;
      ;;
    -*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      break
      ;;
  esac
  shift
done

# Determine the full path to this script.
if [[ ${0:0:1} = / ]]; then
  FULL_PATH="$0"
else
  FULL_PATH="$(realpath $0)"
fi

if test "$opt_foreach" -eq 0; then
  echo "# This file is automatically generated by autogen.sh. Any changes will be overwritten!" > submodules.m4
  git submodule foreach --quiet --recursive "$FULL_PATH --foreach"' $path $toplevel' >> submodules.m4
  if test $(wc --lines < submodules.m4) -gt 1; then
    cat << EOF >> submodules.m4

AC_SUBST([CW_SUBDIRS], "CW_SUBMODULE_SUBDIRS")
AM_SUBST_NOTMAKE([CW_SUBDIRS])
AC_CONFIG_FILES(CW_SUBMODULE_CONFIG_FILES)
EOF
  fi
elif test "$1" != "cwm4"; then
  # Script is called from git submodule foreach ...'
  submodule_path="$1"
  toplevel="$2"
  submodule_rel_path="$rel_top_srcdir${rel_top_srcdir:+/}$submodule_path/"

  echo
  echo "m4_define([cwm4_rel_top_srcdir], [$rel_top_srcdir])"
  echo "m4_define([cwm4_submodule_path], [$submodule_path])"
  echo "m4_define([cwm4_submodule_relpath], [$submodule_rel_path])"
  echo "m4_include([${submodule_rel_path}configure.m4])"
fi
